<a href="https://colab.research.google.com/github/1s5ac/STA365_HW/blob/main/STA365_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. x^(t) counts chip brand purchases over time. As it follows a multinomial distribution, brands with higher purchase probabilities will see faster count increases.

2. Bayesian analysis suggests that beliefs about the "best chips" over time are updated by a Dirichlet distribution, with each new purchase data adjusting its parameters.  The Dirichlet distribution is parameterized by a vector lambda, which would be updated with each observation. The posterior distribution after observing x^(t) is a Dirichlet distribution with parameters lambda+x^(t).

3.

In [5]:
import numpy as np
from scipy.stats import dirichlet

alpha = np.array([2, 5, 2, 1])
size = 10000

samples = dirichlet(alpha).rvs(size=size)
j = 1
p_j_samples = samples[:, j]

4.

In [7]:
import numpy as np
from scipy.stats import dirichlet

alpha = np.array([2, 5, 2, 1])
size = 10000
samples = dirichlet(alpha).rvs(size=size)
q = 0.3
j = 1
prob_p_j_greater_than_q = np.mean(samples[:, j] > q)
prob_p_j_greater_than_q


0.897

5. The interval is [0.2103,  0.7904]

In [8]:
j = 1
credible_interval = np.percentile(samples[:, j], [2.5, 97.5])
credible_interval


array([0.21030755, 0.79037052])

6.

In [9]:
import numpy as np
from scipy.stats import dirichlet

alpha = np.array([2, 5, 2, 1])
size = 10000

samples = dirichlet(alpha).rvs(size=size)
j = 1
j_prime = 2

prob_p_j_greater_than_p_j_prime = np.mean(samples[:, j] > samples[:, j_prime])
prob_p_j_greater_than_p_j_prime


0.8921

7.

In [10]:
import numpy as np
from scipy.stats import dirichlet

alpha = np.array([2, 5, 2, 1])
size = 10000

samples = dirichlet(alpha).rvs(size=size)
j = 1
j_prime = 2

ratios = samples[:, j] / samples[:, j_prime]
interval_estimate = np.percentile(ratios, [2.5, 97.5])
interval_estimate

array([ 0.55483479, 22.67058907])

8.

In [11]:
import numpy as np
from scipy.stats import dirichlet

alpha = np.array([2, 5, 2, 1])
size = 10000

samples = dirichlet(alpha).rvs(size=size)
j = 1
j_prime = 2

differences = samples[:, j] - samples[:, j_prime]
interval_estimate_difference = np.percentile(differences, [2.5, 97.5])
interval_estimate_difference

array([-0.19741925,  0.71507471])

9. The ratios and the differences are measures of relative and absolute advantage, respectively. For (j, j') = (2, 3), since p_2 and p_3 are
quite close in value, the ratio p_2/p_3 is likely to be close to 1,
indicating that neither brand is strongly preferred over the other. The difference p_2-p_3 would also be small, reflecting a small absolute advantage.
The ratio is important when assessing preference strength or dominance of one option over another, while the difference is important when assessing the absolute advantage in terms of probability.

10. If we are examining p_4 and p_5 over time t, assuming that the number of trials (chip purchases) is very large, we would expect the counts of brands 4 and 5 to reflect their probabilities. As t increases, the law of large numbers suggests that the observed frequencies x_4 and x_5 should converge to their expected values, which are np_4 and np_5, respectively. Therefore, the difference in counts should also reflect the probability difference.